using AIStudio.Core.Services;
using FluentAssertions;

namespace AIStudio.Tests;

public class ChatTitleGeneratorTests
{
    // ── IsDefaultTitle ────────────────────────────────────────────────────────

    [Theory]
    [InlineData("Chat 1", true)]
    [InlineData("Chat 42", true)]
    [InlineData("Chat 999", true)]
    [InlineData("Nový chat", false)]
    [InlineData("Moje konverzace", false)]
    [InlineData("Chat", false)]          // bez čísla
    [InlineData("Chat 1 navíc", false)]  // něco za číslem
    [InlineData("", false)]
    [InlineData(null, false)]
    public void IsDefaultTitle_DetectsAutoGenerated(string? title, bool expected)
    {
        ChatTitleGenerator.IsDefaultTitle(title).Should().Be(expected);
    }

    // ── BuildPrompt ───────────────────────────────────────────────────────────

    [Fact]
    public void BuildPrompt_IncludesBothMessages()
    {
        var prompt = ChatTitleGenerator.BuildPrompt("Jak vařit guláš?", "Potřebuješ maso a cibuli.");

        prompt.Should().HaveCount(2);
        prompt[0].Role.Should().Be("system");
        prompt[1].Role.Should().Be("user");
        prompt[1].Content.Should().Contain("Jak vařit guláš?");
        prompt[1].Content.Should().Contain("Potřebuješ maso a cibuli.");
    }

    [Fact]
    public void BuildPrompt_TruncatesLongMessages()
    {
        var longMsg = new string('x', 2000);
        var prompt = ChatTitleGenerator.BuildPrompt(longMsg, "krátká");

        // 800 znaků + „…" + okolní text, ne celých 2000
        prompt[1].Content.Should().Contain("…");
        prompt[1].Content.Length.Should().BeLessThan(2000);
    }

    // ── CleanResponse — hlavní pure logika ────────────────────────────────────

    [Theory]
    [InlineData("Vaření guláše", "Vaření guláše")]
    [InlineData("\"Vaření guláše\"", "Vaření guláše")]
    [InlineData("„Vaření guláše\"", "Vaření guláše")]
    [InlineData("Vaření guláše.", "Vaření guláše")]
    [InlineData("  Vaření guláše  ", "Vaření guláše")]
    public void CleanResponse_StripsQuotesAndPunctuation(string raw, string expected)
    {
        ChatTitleGenerator.CleanResponse(raw).Should().Be(expected);
    }

    [Theory]
    [InlineData("Název: Vaření guláše", "Vaření guláše")]
    [InlineData("Title: Cooking", "Cooking")]
    [InlineData("Pojmenování: Něco", "Něco")]
    [InlineData("Název: \"Vaření\"", "Vaření")]
    public void CleanResponse_StripsPrefixes(string raw, string expected)
    {
        ChatTitleGenerator.CleanResponse(raw).Should().Be(expected);
    }

    [Fact]
    public void CleanResponse_TakesFirstLineOnly()
    {
        ChatTitleGenerator.CleanResponse("Vaření guláše\nNějaké vysvětlení navíc")
            .Should().Be("Vaření guláše");
    }

    [Fact]
    public void CleanResponse_TruncatesToMaxLength()
    {
        var raw = new string('A', 100);
        var result = ChatTitleGenerator.CleanResponse(raw);
        result!.Length.Should().Be(60);
    }

    [Theory]
    [InlineData("")]
    [InlineData("   ")]
    [InlineData(null)]
    [InlineData("\"\"")]    // jen uvozovky → po trimu prázdné
    [InlineData("A")]       // kratší než minimum (2)
    public void CleanResponse_InvalidInput_ReturnsNull(string? raw)
    {
        ChatTitleGenerator.CleanResponse(raw).Should().BeNull();
    }

    [Fact]
    public void CleanResponse_RealisticLlmOutput_CleansProperly()
    {
        // Typický „ukecaný" výstup malého modelu
        var raw = "Název: \"Recept na guláš\"\nDoufám, že to pomůže!";
        ChatTitleGenerator.CleanResponse(raw).Should().Be("Recept na guláš");
    }
}
